name: Init

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}' 
  deploy:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('composer.json') == '' }}
    steps:
      - run: echo "no composer"
