name: deploy

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}' 
  deploy:
    runs-on: ubuntu-latest
    if: github.run_number == 1 && github.event.repository.default_branch
    steps:
      - run: ./bin/util/new-laravel-project "${{ github.event.repository.name }}"
